### PR TITLE
Fix #173: en_GB incorrectly resets to en_US for date pickers

### LINKED ISSUE #173: en_GB incorrectly resets to en_US for date pickers
2024-01-26 at 18 20 18

As can be seen, US-style date pickers are being used – the week starts on Sunday rather than Monday; the date is MM/DD/YYYY rather than DD/MM/YYYY – even though for this screenshot the language is set to en_GB. Because the localisation file is `en.lproj`, the following branch is followed no matter what, resetting localisation to `en_US`:

https://github.com/DamascenoRafael/reminders-menubar/blob/d92d2053aeaecea9471fc1409196da0ad3a42cdf/reminders-menubar/Resources/remindersLocalized.swift#L108-L110

### PR DESCRIPTION
**Pull request by yunruse**
Reliably fixes #173 on my machine, and has no obvious breakage even when e.g. the language is set to `fr_CA`.

Changes 'does language exist' check to use `Bundle.main.localizations` rather than `.lproj` pathing on both the locale code and the language code before defaulting to `en_US`.

### CODE REVIEW

File: reminders-menubar/Resources/remindersLocalized.swift [hunk 1]
```diff
@@ -105,7 +105,8 @@ func rmbCurrentLocale() -> Locale {
     if let preferredLanguage = UserPreferences.shared.preferredLanguage {
         currentLocale = Locale(identifier: preferredLanguage)
     }
-    if Bundle.main.path(forResource: currentLocale.identifier, ofType: "lproj") == nil {
+    let Has = Bundle.main.localizations.contains
+    if !(Has(currentLocale.identifier) || Has(currentLocale.languageCode ?? "")) {
```
Comment (DamascenoRafael) [inline reminders-menubar/Resources/remindersLocalized.swift:109]: small change to make it clearer what the variable means and to eliminate the linter error about variable starting with a capital letter.

```suggestion
    let containsLocalization = Bundle.main.localizations.contains
    if !(containsLocalization(currentLocale.identifier) || containsLocalization(currentLocale.languageCode ?? "")) {
```

Comment (DamascenoRafael) [reply reminders-menubar/Resources/remindersLocalized.swift]: Don't worry about the linter, this project is using [SwiftLint](https://github.com/realm/SwiftLint), but it's not a blocker not using it.

Within a small scope, using a short name (like just a verb) can be ok, but even so, trying a name that makes it more explicit is usually more recommended. You can check, for example, that in line 107 I'm using `var currentLocale = Locale.current` and not just `var current = Locale.current`.

Taking a closer look at the results of your changes, I think a more interesting approach would be to not have a fallback for en_US.

What is happening for en_GB is that en_GB is being used everywhere that `rmbCurrentLocale()` is called (date pickers, date formatters and relative date formatting). But when using the translated strings for the app, a fallback to en_US is occurring (within the `rmbLocalized` function in `let localeBundle = Bundle(path: localePath) ?? Bundle.main`).

So I think I'll change it so that whenever "use system language" is enabled, the system language will be used whenever possible. Meaning that for a language that is not in the app, all strings will be in en_US, but the date picker, date formatters and relative date formatting will be in the system language.

Let me know what you think of this approach. I will add it as a suggestion for the code.

File: reminders-menubar/Resources/remindersLocalized.swift [hunk 2]
```diff
@@ -105,7 +105,8 @@ func rmbCurrentLocale() -> Locale {
     if let preferredLanguage = UserPreferences.shared.preferredLanguage {
         currentLocale = Locale(identifier: preferredLanguage)
     }
-    if Bundle.main.path(forResource: currentLocale.identifier, ofType: "lproj") == nil {
+    let exists = Bundle.main.localizations.contains
+    if !(exists(currentLocale.identifier) || exists(currentLocale.languageCode ?? "")) {
         // Return the default locale if translation to system language does not exist
         return Locale(identifier: "en_US")
     }
```
Comment (DamascenoRafael) [inline reminders-menubar/Resources/remindersLocalized.swift:112]:
```suggestion
```

As mentioned in the PR

Comment (DamascenoRafael) [reply reminders-menubar/Resources/remindersLocalized.swift:112]: This way will return `Locale.current` or `preferredLanguage`

File: reminders-menubar/Resources/remindersLocalized.swift (hunk 1 above)
Comment (yunruse) [reply reminders-menubar/Resources/remindersLocalized.swift]: Ah! I had assumed because it was `en.lproj` that whatever Swift magic was at work (mind my naïvete in the language) auto-resolved both `en_gb` and `en_us` to use these strings, and that by dint of there being no `en_us.lproj` bundle both locales would silently follow the code path.

Thanks for the suggestion!

**Comment by DamascenoRafael** [comment]
Thank you for putting effort into this! 🚀 
Merging and closing the related issue.
